/* Ten sentences per card, cycled one per viewing. Generated from
   contexts.json - edit that, not this. */
window.CONTEXTS = {
 "enhance": [
  "A little salt will *enhance* the flavour of almost any soup.",
  "New lighting would *enhance* the room without costing much.",
  "She took a short course to *enhance* her chances of promotion.",
  "Good speakers really do *enhance* the experience of a film.",
  "Walking to work each morning *enhanced* his mood all day.",
  "The gallery added plain frames to *enhance* the paintings.",
  "A second coat of paint *enhances* the colour underneath.",
  "They hoped the new pitch would *enhance* the club's reputation.",
  "Reading widely *enhances* your vocabulary more than any app.",
  "A slow cook time *enhances* the sweetness of the onions."
 ],
 "compassion": [
  "The nurse spoke to every patient with real *compassion*, even at the end of a long shift.",
  "He showed great *compassion* towards the family who had lost everything.",
  "Her *compassion* for stray animals kept the shelter running for years.",
  "A judge can apply the law and still show *compassion*.",
  "The letter was full of *compassion* rather than advice.",
  "Teaching children *compassion* matters as much as teaching them maths.",
  "She listened without judging, which is *compassion* in practice.",
  "There was no *compassion* in the way the news was delivered.",
  "Treating yourself with *compassion* is harder than being kind to others.",
  "The charity was founded out of *compassion*, not profit."
 ],
 "thrive on": [
  "Some people *thrive on* pressure and do their best work close to a deadline.",
  "Young plants *thrive on* light, water and very little else.",
  "She seems to *thrive on* having three projects running at once.",
  "Street markets *thrive on* crowds, so a quiet day hurts them.",
  "He *thrives on* competition and gets bored without it.",
  "These birds *thrive on* the insects that live in old woodland.",
  "Small cafes *thrive on* regulars who come in every morning.",
  "Children *thrive on* routine far more than adults expect.",
  "The band *thrived on* playing live rather than recording.",
  "Rumours *thrive on* silence, so the company finally spoke."
 ],
 "impact": [
  "The new rule had a real *impact* on how people travelled to work.",
  "Losing the contract had a serious *impact* on the whole team.",
  "One good teacher can have a lasting *impact* on a child.",
  "The report measured the *impact* of the flood on local shops.",
  "Her speech made an immediate *impact* on everyone in the room.",
  "Cutting the bus route had little *impact* at first.",
  "Scientists are studying the *impact* of warmer winters on crops.",
  "The advert had more *impact* than the company expected.",
  "Rising rent has the biggest *impact* on younger tenants.",
  "He wanted his work to have an *impact* beyond his own city."
 ],
 "commitment": [
  "Learning an instrument takes real *commitment* over several years.",
  "She made a firm *commitment* to finish the course by June.",
  "The club thanked him for twenty years of *commitment*.",
  "A puppy is a ten-year *commitment*, not a weekend idea.",
  "Their *commitment* to the project never wavered.",
  "He could not give a *commitment* until he had seen the budget.",
  "Marriage is a *commitment* people enter with their eyes open.",
  "The company made a public *commitment* to cut its waste.",
  "Training every morning shows a level of *commitment* few have.",
  "Without *commitment* from the staff, the plan would fail."
 ],
 "flunk out of": [
  "He nearly *flunked out of* university in his first year before he found his feet.",
  "She was warned she might *flunk out of* the programme if she missed more classes.",
  "Two students *flunked out of* the course after failing every module.",
  "He was terrified he would *flunk out of* medical school.",
  "Missing the exams meant he *flunked out of* college that spring.",
  "Nobody expected the top student to *flunk out of* the year.",
  "She worked nights and almost *flunked out of* her degree.",
  "He *flunked out of* his first course and started again elsewhere.",
  "The pressure made several people *flunk out of* the programme.",
  "You will not *flunk out of* the class for one bad essay."
 ],
 "conversely": [
  "City rents keep rising; *conversely*, rural homes are getting cheaper.",
  "Older workers valued security. *Conversely*, younger ones wanted flexibility.",
  "Some plants need full sun. *Conversely*, ferns prefer deep shade.",
  "Sales rose in the north. *Conversely*, they fell in the south.",
  "He speaks quickly when nervous; *conversely*, she goes silent.",
  "Winters here are mild. *Conversely*, the summers are brutal.",
  "The film was praised abroad and, *conversely*, ignored at home.",
  "Small firms hired more staff. *Conversely*, large ones cut jobs.",
  "Reading before bed relaxes him. *Conversely*, it keeps her awake.",
  "Prices fell in spring and, *conversely*, rose sharply in autumn."
 ],
 "arguably": [
  "That is *arguably* the best album the band ever made.",
  "She is *arguably* the finest goalkeeper in the league.",
  "This is *arguably* the most important decision of his career.",
  "The bridge is *arguably* the ugliest building in the city.",
  "It was *arguably* cheaper to repair the car than replace it.",
  "He is *arguably* too young for such a senior post.",
  "That match was *arguably* the turning point of the season.",
  "Rain is *arguably* the main reason the crop failed.",
  "The old route was *arguably* safer, if a little slower.",
  "Her first novel is *arguably* still her strongest."
 ],
 "notwithstanding": [
  "The team played well, *notwithstanding* the terrible weather.",
  "*Notwithstanding* his age, he still runs every morning.",
  "The shop stayed open, *notwithstanding* the roadworks outside.",
  "She took the job, *notwithstanding* the long commute.",
  "*Notwithstanding* the cost, the repair had to be done.",
  "He remains popular, *notwithstanding* the criticism.",
  "The flight left on time, *notwithstanding* the fog.",
  "*Notwithstanding* a slow start, the book sold well.",
  "They finished the build, *notwithstanding* two strikes.",
  "The plan went ahead, *notwithstanding* several objections."
 ],
 "albeit": [
  "The meal was good, *albeit* a little expensive.",
  "He agreed to help, *albeit* reluctantly.",
  "She won the race, *albeit* by a very narrow margin.",
  "The flat is lovely, *albeit* rather small.",
  "Sales improved, *albeit* more slowly than hoped.",
  "He answered the question, *albeit* without much detail.",
  "The train arrived, *albeit* forty minutes late.",
  "It was a fair offer, *albeit* not a generous one.",
  "She smiled, *albeit* briefly, when she saw him.",
  "The weather improved, *albeit* only for an afternoon."
 ],
 "inherently": [
  "Climbing without ropes is *inherently* dangerous.",
  "There is nothing *inherently* wrong with changing your mind.",
  "Some jobs are *inherently* stressful, whatever the pay.",
  "The system was *inherently* unfair to part-time staff.",
  "Small boats are *inherently* less stable in rough water.",
  "Predicting the weather is *inherently* difficult.",
  "The plan was *inherently* risky from the start.",
  "Children are *inherently* curious about how things work.",
  "Cash payments are *inherently* harder to trace.",
  "The argument is *inherently* weak without evidence."
 ],
 "predominantly": [
  "The audience was *predominantly* students and young families.",
  "This area is *predominantly* farmland.",
  "The staff are *predominantly* women under thirty.",
  "Her work is *predominantly* in watercolour.",
  "The diet there is *predominantly* fish and rice.",
  "Complaints came *predominantly* from older residents.",
  "The village is *predominantly* quiet outside the summer.",
  "He works *predominantly* at night.",
  "The town's income is *predominantly* from tourism.",
  "The band's fans are *predominantly* from the north."
 ],
 "invariably": [
  "He *invariably* arrives ten minutes early.",
  "The last train is *invariably* crowded.",
  "She *invariably* orders the same coffee.",
  "Plans made in a hurry *invariably* go wrong.",
  "The dog *invariably* barks at the postman.",
  "Cheap tools *invariably* break within a year.",
  "He *invariably* forgets his umbrella.",
  "Meetings that long *invariably* lose people's attention.",
  "The queue on a Friday is *invariably* long.",
  "She *invariably* knows the answer before anyone else."
 ],
 "inadvertently": [
  "He *inadvertently* deleted the file while tidying his folders.",
  "She *inadvertently* gave away the surprise.",
  "I *inadvertently* left the gate open.",
  "The email was *inadvertently* sent to the whole office.",
  "He *inadvertently* stepped on the sleeping cat.",
  "They *inadvertently* booked the flight for the wrong day.",
  "She *inadvertently* insulted him by mentioning his old job.",
  "The builder *inadvertently* cut through a water pipe.",
  "I *inadvertently* took someone else's coat.",
  "He *inadvertently* revealed the price during the meeting."
 ],
 "paradoxically": [
  "*Paradoxically*, the quietest students often write the best essays.",
  "Sleeping more can, *paradoxically*, make you feel more tired at first.",
  "*Paradoxically*, the cheaper shop was further from the poorer streets.",
  "*Paradoxically*, adding lanes often makes traffic worse.",
  "He grew, *paradoxically*, more relaxed as the deadline came closer.",
  "*Paradoxically*, the warmest room in the house is the smallest.",
  "*Paradoxically*, practising less that week improved her playing.",
  "The rule, *paradoxically*, protected the people it was meant to limit.",
  "*Paradoxically*, the film got better reviews after it flopped.",
  "Eating slowly, *paradoxically*, leaves you fuller on less."
 ],
 "akin to": [
  "The feeling was *akin to* homesickness, though he was at home.",
  "Her voice is *akin to* her mother's on the phone.",
  "Riding it is *akin to* steering a boat.",
  "The noise was *akin to* a kettle coming to the boil.",
  "His job is *akin to* being a referee all day.",
  "The taste is *akin to* burnt caramel.",
  "That approach is *akin to* guessing.",
  "The pain was *akin to* a bad toothache.",
  "Learning chess is *akin to* learning a language.",
  "The smell was *akin to* wet hay."
 ],
 "ubiquitous": [
  "Coffee shops are so *ubiquitous* now that there is one on every corner.",
  "Mobile phones are *ubiquitous*, even in the smallest villages.",
  "Seagulls are *ubiquitous* along this stretch of coast.",
  "Plastic packaging has become *ubiquitous* in supermarkets.",
  "That song was *ubiquitous* the summer it came out.",
  "Bicycles are *ubiquitous* in the flatter parts of the country.",
  "Cameras are now *ubiquitous* in city centres.",
  "The logo is *ubiquitous*, yet few people know the company.",
  "Free wifi is *ubiquitous* in hotels these days.",
  "Complaints about the weather are *ubiquitous* here."
 ],
 "a blessing in disguise": [
  "Missing that train turned out to be *a blessing in disguise*, because the meeting was cancelled anyway.",
  "Losing that job was *a blessing in disguise*; she started her own business a month later.",
  "The rain was *a blessing in disguise* and saved the garden.",
  "Breaking his ankle was *a blessing in disguise*, as the rest healed an older injury.",
  "The delay was *a blessing in disguise* and they avoided the storm.",
  "Being turned down felt awful, but it was *a blessing in disguise*.",
  "The power cut was *a blessing in disguise*; everyone talked for once.",
  "Moving to a smaller flat was *a blessing in disguise*.",
  "That bad review was *a blessing in disguise* and forced a rewrite.",
  "Selling the car proved *a blessing in disguise* once he started walking."
 ],
 "the tip of the iceberg": [
  "The missing files were only *the tip of the iceberg*, as the audit later showed.",
  "Those complaints are *the tip of the iceberg*.",
  "The leak was *the tip of the iceberg* in a much older problem.",
  "What you see on the bill is *the tip of the iceberg*.",
  "Two resignations were *the tip of the iceberg* that month.",
  "The damp patch was *the tip of the iceberg*, and the whole wall came out.",
  "That argument was *the tip of the iceberg* in their marriage.",
  "The fine was *the tip of the iceberg* compared with the legal costs.",
  "One late delivery is *the tip of the iceberg* here.",
  "His tiredness was *the tip of the iceberg*."
 ],
 "prevalent": [
  "Colds are more *prevalent* in the winter months.",
  "That accent is *prevalent* across the whole county.",
  "Cash payments are still *prevalent* at local markets.",
  "The belief was *prevalent* long before anyone tested it.",
  "Damp is *prevalent* in houses of that age.",
  "Short contracts are *prevalent* in the industry now.",
  "The disease is most *prevalent* among older cattle.",
  "Scams of that kind are *prevalent* around the holidays.",
  "Flat caps were *prevalent* in photographs from that decade.",
  "Anxiety is *prevalent* among students in exam term."
 ],
 "a double-edged sword": [
  "Fame is *a double-edged sword*: it opens doors and closes others.",
  "Working from home is *a double-edged sword* for a lot of people.",
  "The grant was *a double-edged sword*, as it came with conditions.",
  "Being the tallest player is *a double-edged sword*.",
  "Cheap flights are *a double-edged sword* for small islands.",
  "Her honesty is *a double-edged sword* at work.",
  "The new road is *a double-edged sword* for the village.",
  "Winning early was *a double-edged sword* for the team.",
  "Social media is *a double-edged sword* for small shops.",
  "A big inheritance can be *a double-edged sword*."
 ],
 "detrimental": [
  "Too much screen time is *detrimental* to sleep.",
  "The delay was *detrimental* to the whole project.",
  "Skipping breakfast can be *detrimental* to concentration.",
  "The new rules proved *detrimental* to small farmers.",
  "Salt in that quantity is *detrimental* to the soil.",
  "Constant noise is *detrimental* to learning.",
  "The story was *detrimental* to his reputation.",
  "Overwatering is *detrimental* to most houseplants.",
  "Long hours are *detrimental* to family life.",
  "The change was *detrimental* to staff morale."
 ],
 "negligible": [
  "The difference in price was *negligible*, so she took the nearer one.",
  "The damage to the car was *negligible*.",
  "Rain that light has a *negligible* effect on the crop.",
  "The delay was *negligible* compared with the usual traffic.",
  "His share of the cost was *negligible*.",
  "The risk is *negligible* if you follow the instructions.",
  "The savings turned out to be *negligible*.",
  "A *negligible* amount of heat escapes through the new glass.",
  "The noise from the fan is *negligible*.",
  "The weight difference is *negligible* over a short walk."
 ],
 "substantial": [
  "They received a *substantial* sum after the sale of the house.",
  "There has been a *substantial* rise in bus fares.",
  "He made a *substantial* contribution to the repair fund.",
  "The meal was *substantial* enough to last until evening.",
  "A *substantial* part of the roof needed replacing.",
  "The report offered *substantial* evidence for the claim.",
  "There is a *substantial* difference between the two offers.",
  "The company made a *substantial* loss last year.",
  "She has *substantial* experience in the field.",
  "The building needs *substantial* work before anyone moves in."
 ],
 "viable": [
  "Cycling is only a *viable* option if the weather holds.",
  "The plan is not *viable* on that budget.",
  "They needed a *viable* alternative to the ferry.",
  "Solar became *viable* here once the panels got cheaper.",
  "The shop was never *viable* in such a quiet street.",
  "Is it *viable* to finish the work in one weekend?",
  "The seeds are still *viable* after three years.",
  "Only one route was *viable* in the snow.",
  "The business became *viable* after they cut the rent.",
  "A four-day week proved *viable* for the small team."
 ],
 "cut corners": [
  "The builders *cut corners* on the roof, and it leaked within a year.",
  "Do not *cut corners* when you are wiring a house.",
  "They *cut corners* to meet the deadline and paid for it later.",
  "You can see where the previous owner *cut corners*.",
  "The company *cut corners* on training.",
  "He never *cuts corners*, even on small jobs.",
  "Trying to *cut corners* with the paint ruined the finish.",
  "They *cut corners* on safety and were fined.",
  "She refused to *cut corners* on the research.",
  "Restaurants that *cut corners* on ingredients lose regulars."
 ],
 "sustainable": [
  "The farm uses *sustainable* methods that keep the soil healthy.",
  "Working seventy hours a week is not *sustainable*.",
  "They wanted a *sustainable* source of timber.",
  "The pace of spending simply is not *sustainable*.",
  "*Sustainable* fishing quotas were agreed at last.",
  "The charity needs a *sustainable* income, not one big gift.",
  "He found a more *sustainable* way to train.",
  "The packaging is fully *sustainable* now.",
  "That level of growth is not *sustainable* forever.",
  "They built the school with *sustainable* materials."
 ],
 "pragmatic": [
  "She took a *pragmatic* view and fixed what could be fixed.",
  "A *pragmatic* solution beat a perfect one that day.",
  "He is *pragmatic* about money.",
  "The council took a *pragmatic* approach to the parking problem.",
  "Being *pragmatic*, they cancelled the outdoor part.",
  "A *pragmatic* leader knows which battles to skip.",
  "Her advice was *pragmatic* rather than comforting.",
  "They made a *pragmatic* decision to sell early.",
  "He is idealistic at home and *pragmatic* at work.",
  "The *pragmatic* choice was to repair, not replace."
 ],
 "compelling": [
  "The evidence was *compelling*, and the jury agreed quickly.",
  "She made a *compelling* case for the extra funding.",
  "It was a *compelling* film from the first minute.",
  "There is no *compelling* reason to move.",
  "His argument was *compelling* but wrong.",
  "The book is *compelling* despite its length.",
  "They gave a *compelling* account of the night.",
  "The offer was *compelling* enough to accept on the spot.",
  "Her performance was the most *compelling* on the night.",
  "The data tells a *compelling* story."
 ],
 "plausible": [
  "His excuse sounded *plausible* until we checked the dates.",
  "That is a *plausible* explanation for the noise.",
  "She gave a *plausible* account of where the money went.",
  "It seems *plausible* that the fault started in the wiring.",
  "The theory is *plausible* but hard to prove.",
  "He could not think of a *plausible* reason to leave early.",
  "A *plausible* forecast is better than a confident wrong one.",
  "The story was *plausible* enough to fool the bank.",
  "There is no *plausible* way he walked that far in an hour.",
  "It is *plausible* that the two events are connected."
 ],
 "bite the bullet": [
  "He finally decided to *bite the bullet* and tell his boss he was leaving.",
  "We had to *bite the bullet* and pay for a new boiler.",
  "She *bit the bullet* and booked the dentist.",
  "At some point you have to *bite the bullet* and start writing.",
  "They *bit the bullet* and closed the smaller shop.",
  "I *bit the bullet* and asked for a pay rise.",
  "You will have to *bite the bullet* and apologise.",
  "He *bit the bullet* and sat the exam again.",
  "They decided to *bite the bullet* and rewire the whole house.",
  "She *bit the bullet* and moved back home for a year."
 ],
 "ambiguous": [
  "The instructions were *ambiguous*, so half the class did it wrong.",
  "His answer was deliberately *ambiguous*.",
  "The ending of the film is *ambiguous*.",
  "That word is *ambiguous* without more context.",
  "The contract was *ambiguous* about who paid for repairs.",
  "She gave an *ambiguous* smile that could have meant anything.",
  "The sign was *ambiguous* and drivers kept turning early.",
  "His feelings about the move were *ambiguous*.",
  "An *ambiguous* question makes the results useless.",
  "The results were *ambiguous* and the trial was repeated."
 ],
 "disproportionate": [
  "The punishment felt *disproportionate* to the offence.",
  "A *disproportionate* share of the work fell to her.",
  "The response was *disproportionate* to a minor complaint.",
  "Housing takes a *disproportionate* amount of his income.",
  "A *disproportionate* number of injuries happen in the last ten minutes.",
  "The coverage was *disproportionate* to how rare the event was.",
  "Small firms carry a *disproportionate* burden of the paperwork.",
  "He spent a *disproportionate* amount of time on the title.",
  "The fee is *disproportionate* to the service provided.",
  "A *disproportionate* part of the budget went on the launch."
 ],
 "disparate": [
  "The committee brought together *disparate* groups who rarely agreed.",
  "The evidence came from *disparate* sources.",
  "Her interests are wildly *disparate*, from welding to ballet.",
  "The band members had *disparate* tastes in music.",
  "The town joined two *disparate* communities.",
  "They collected *disparate* facts and looked for a pattern.",
  "The report covers *disparate* topics with no clear thread.",
  "Two *disparate* styles sit side by side in the house.",
  "The list is a *disparate* collection of old notes.",
  "*Disparate* teams were merged into one department."
 ],
 "unprecedented": [
  "The heat that summer was *unprecedented* for the region.",
  "Demand reached *unprecedented* levels after the advert.",
  "It was an *unprecedented* step for such a cautious company.",
  "The floods caused *unprecedented* damage to the valley.",
  "She won by an *unprecedented* margin.",
  "The library saw *unprecedented* numbers that winter.",
  "An *unprecedented* number of people voted early.",
  "The delay was *unprecedented* on that line.",
  "They faced *unprecedented* pressure to publish.",
  "The move was *unprecedented* in the club history."
 ],
 "robust": [
  "The old table is *robust* enough to stand on.",
  "They built a *robust* system that rarely fails.",
  "He gave a *robust* defence of the decision.",
  "The economy proved more *robust* than expected.",
  "These boots are *robust* and will last years.",
  "The plan needs a *robust* backup.",
  "She is in *robust* health at eighty.",
  "The bridge is *robust*, despite its age.",
  "We need *robust* evidence before publishing.",
  "The frame is light but surprisingly *robust*."
 ],
 "get the hang of": [
  "It took a week to *get the hang of* the new software.",
  "Once you *get the hang of* it, driving becomes automatic.",
  "She soon *got the hang of* making bread.",
  "He never quite *got the hang of* skiing.",
  "Give it time and you will *get the hang of* the rhythm.",
  "I am starting to *get the hang of* the new phone.",
  "They *got the hang of* the route after a few trips.",
  "It is fiddly until you *get the hang of* it.",
  "She *got the hang of* the accent within a month.",
  "You will *get the hang of* the machine by Friday."
 ],
 "profound": [
  "The book had a *profound* effect on how he saw his childhood.",
  "There was a *profound* silence after the news.",
  "She has a *profound* knowledge of the period.",
  "The loss left a *profound* mark on the family.",
  "His words had a *profound* influence on the movement.",
  "A *profound* change came over the town after the mine closed.",
  "The film asks *profound* questions without answering them.",
  "There is a *profound* difference between the two approaches.",
  "He felt a *profound* relief when the results came.",
  "The essay shows a *profound* understanding of the subject."
 ],
 "inevitable": [
  "With that many delays, a missed deadline was *inevitable*.",
  "It is *inevitable* that prices will rise again.",
  "The argument felt *inevitable* from the start of the evening.",
  "Rust is *inevitable* on a car of that age.",
  "Some disappointment is *inevitable* in any big project.",
  "The *inevitable* happened and the shed blew over.",
  "Change was *inevitable* once the new manager arrived.",
  "It seemed *inevitable* that they would move abroad.",
  "Tiredness is *inevitable* after a week like that.",
  "The *inevitable* questions came at the end of the talk."
 ],
 "intricate": [
  "The lock has an *intricate* mechanism that few can repair.",
  "She painted an *intricate* pattern around the edge.",
  "The plot is *intricate* and needs a second reading.",
  "The carving was *intricate*, right down to the leaves.",
  "They worked out an *intricate* schedule for the week.",
  "The map showed an *intricate* network of paths.",
  "His argument is *intricate* but sound.",
  "The watch has an *intricate* set of gears.",
  "An *intricate* series of steps was needed.",
  "The lace was so *intricate* it took months."
 ],
 "rudimentary": [
  "He has a *rudimentary* grasp of Spanish, enough to order food.",
  "The hut had only *rudimentary* plumbing.",
  "Her *rudimentary* first aid was enough until help arrived.",
  "The first version had a *rudimentary* design.",
  "They had a *rudimentary* map drawn on a napkin.",
  "The tools were *rudimentary* but they finished the job.",
  "He gave a *rudimentary* explanation of how engines work.",
  "The school had *rudimentary* equipment and brilliant teachers.",
  "My *rudimentary* cooking improved after the course.",
  "A *rudimentary* shelter kept the rain off."
 ],
 "on the same page": [
  "Before we start, let us make sure everyone is *on the same page*.",
  "The two departments were not *on the same page* about the budget.",
  "A quick call got us *on the same page*.",
  "They are finally *on the same page* about the wedding.",
  "The team needs to be *on the same page* before the match.",
  "We were not *on the same page*, which caused the mix-up.",
  "Getting *on the same page* early saves arguments later.",
  "He checked they were *on the same page* about the price.",
  "The partners are *on the same page* for once.",
  "A shared document keeps everyone *on the same page*."
 ],
 "arduous": [
  "The climb was *arduous*, and they rested every hour.",
  "It was an *arduous* journey across the moor in the rain.",
  "Sorting thirty years of paperwork proved *arduous*.",
  "The training is *arduous* but the pay is good.",
  "They faced an *arduous* week of rehearsals.",
  "Learning the alphabet again was *arduous* for him.",
  "The last mile was the most *arduous*.",
  "Restoring the boat was an *arduous* task.",
  "She found the daily commute *arduous*.",
  "The *arduous* process took most of the winter."
 ],
 "futile": [
  "Arguing with him at that point was *futile*.",
  "Their efforts to save the tree were *futile*.",
  "It is *futile* to water the garden in full sun.",
  "He made one last, *futile* attempt to start the engine.",
  "Complaining after the deadline is *futile*.",
  "The search proved *futile* after three days.",
  "It felt *futile* to keep tidying with the builders in.",
  "Any protest would have been *futile*.",
  "She gave a *futile* shrug and walked away.",
  "Chasing the bus was *futile*, but he tried."
 ],
 "tangible": [
  "After months of work there was finally something *tangible* to show.",
  "The benefits were *tangible* within a fortnight.",
  "There is no *tangible* evidence of a break-in.",
  "A pay rise is more *tangible* than praise.",
  "The mood in the room was almost *tangible*.",
  "They wanted *tangible* results, not promises.",
  "The repairs made a *tangible* difference to the noise.",
  "He needed something *tangible* to hold onto.",
  "The *tangible* cost is only part of the story.",
  "Progress became *tangible* once the roof went on."
 ],
 "pivotal": [
  "That save was *pivotal* in winning the match.",
  "She played a *pivotal* role in setting up the charity.",
  "The meeting proved *pivotal* for the whole company.",
  "His evidence was *pivotal* to the case.",
  "That year was *pivotal* in her life.",
  "The bridge is *pivotal* to the local economy.",
  "A *pivotal* moment came halfway through the film.",
  "The decision was *pivotal*, though it seemed small.",
  "He held a *pivotal* position in the team.",
  "The invention was *pivotal* to modern farming."
 ],
 "in the long run": [
  "Buying good boots is cheaper *in the long run*.",
  "*In the long run*, the extra insulation will pay for itself.",
  "Skipping practice hurts you *in the long run*.",
  "It is better *in the long run* to fix it properly.",
  "The move made sense *in the long run*.",
  "*In the long run*, walking to work saved him a fortune.",
  "It will be easier *in the long run* to learn the shortcuts.",
  "The cheaper option costs more *in the long run*.",
  "*In the long run*, honesty saved the friendship.",
  "The training is hard but worth it *in the long run*."
 ],
 "exacerbate": [
  "Shouting only *exacerbated* the situation.",
  "The drought was *exacerbated* by the leaking pipes.",
  "Cold air can *exacerbate* a cough.",
  "The delay *exacerbated* an already tense mood.",
  "Cutting the bus route *exacerbated* the traffic.",
  "Do not *exacerbate* the problem by guessing.",
  "His comments *exacerbated* the argument.",
  "Poor drainage *exacerbates* the flooding every winter.",
  "The shortage was *exacerbated* by panic buying.",
  "Late nights *exacerbate* the tiredness."
 ],
 "mitigate": [
  "Planting trees helps *mitigate* the noise from the road.",
  "They took steps to *mitigate* the damage.",
  "Nothing could *mitigate* the disappointment.",
  "Sandbags *mitigated* the worst of the flooding.",
  "The company acted to *mitigate* the losses.",
  "A cushion of savings *mitigates* the risk.",
  "Shade cloth *mitigates* the heat in the greenhouse.",
  "They tried to *mitigate* the effect on staff.",
  "Early treatment can *mitigate* the symptoms.",
  "Good insulation *mitigates* the cost of heating."
 ],
 "alleviate": [
  "A hot drink helped *alleviate* the cold.",
  "The new road *alleviated* the congestion in the village.",
  "Nothing seemed to *alleviate* his worry.",
  "Painkillers *alleviated* the worst of it.",
  "Extra staff *alleviated* the pressure on the ward.",
  "Music can *alleviate* boredom on a long drive.",
  "The grant *alleviated* some of the family hardship.",
  "Stretching *alleviates* the stiffness in his back.",
  "A short walk *alleviates* the afternoon slump.",
  "The shelter *alleviated* the worst of the wind."
 ],
 "take it with a pinch of salt": [
  "He tells good stories, but you should *take it with a pinch of salt*.",
  "The survey looked convincing, though experts said to *take it with a pinch of salt*.",
  "Take the advert seriously, but *take it with a pinch of salt*.",
  "She hears a lot of gossip and has learned to *take it with a pinch of salt*.",
  "The forecast that far ahead? *Take it with a pinch of salt*.",
  "His account was lively, so we *took it with a pinch of salt*.",
  "Any figure from that site, *take it with a pinch of salt*.",
  "He said the fish was enormous; we *took it with a pinch of salt*.",
  "Reviews from one night only, *take it with a pinch of salt*.",
  "The estimate sounded low, so they *took it with a pinch of salt*."
 ],
 "undermine": [
  "Constant criticism can *undermine* a child confidence.",
  "The leak *undermined* trust in the whole department.",
  "Heavy rain had *undermined* the wall.",
  "His jokes *undermined* the seriousness of the meeting.",
  "Missing deadlines *undermines* your case for promotion.",
  "The rumour *undermined* months of careful work.",
  "Do not *undermine* your own argument with a guess.",
  "The scandal *undermined* the charity reputation.",
  "Poor sleep *undermines* everything else you do.",
  "Cheap parts *undermine* the whole repair."
 ],
 "underpin": [
  "Strong foundations *underpin* the entire building.",
  "Trust *underpins* every good working relationship.",
  "Careful research *underpins* her argument.",
  "Cheap energy *underpinned* the growth of the town.",
  "Several studies *underpin* the new guidance.",
  "Volunteers *underpin* the whole festival.",
  "A simple idea *underpins* the design.",
  "Savings *underpin* their sense of security.",
  "Rules *underpin* a fair game.",
  "The grant *underpins* the whole programme."
 ],
 "facilitate": [
  "The new app should *facilitate* booking a table.",
  "A neutral chair can *facilitate* a difficult discussion.",
  "The bridge *facilitates* trade between the two towns.",
  "Good lighting *facilitates* accurate work.",
  "She was asked to *facilitate* the workshop.",
  "The grant *facilitated* the move to bigger premises.",
  "Clear signs *facilitate* the flow of people.",
  "The software *facilitates* sharing between offices.",
  "Early booking *facilitates* a cheaper fare.",
  "A common language *facilitates* the whole project."
 ],
 "hinder": [
  "Heavy snow *hindered* the rescue effort.",
  "Poor lighting *hinders* accurate work.",
  "Do not let fear *hinder* you.",
  "The roadworks *hindered* deliveries all week.",
  "A lack of funding *hindered* the research.",
  "His bad knee *hinders* him on stairs.",
  "Too many meetings *hinder* actual progress.",
  "The wind *hindered* the swimmers.",
  "Nothing was allowed to *hinder* the opening.",
  "Long forms *hinder* people from applying."
 ],
 "go the extra mile": [
  "The staff always *go the extra mile* for regulars.",
  "She *went the extra mile* and delivered it herself.",
  "You have to *go the extra mile* to stand out.",
  "He *goes the extra mile* with every repair.",
  "The hotel *went the extra mile* after the mix-up.",
  "Teachers there *go the extra mile* for their pupils.",
  "They *went the extra mile* to find the missing part.",
  "It pays to *go the extra mile* early on.",
  "She *goes the extra mile* without being asked.",
  "Small firms *go the extra mile* to keep customers."
 ],
 "curb": [
  "The council brought in parking charges to *curb* traffic in the centre.",
  "He is trying to *curb* his spending before Christmas.",
  "New rules aim to *curb* noise after eleven.",
  "She could not *curb* her curiosity and opened the box.",
  "A fence was put up to *curb* the erosion.",
  "They *curbed* the outbreak by closing the ward.",
  "Higher fares did little to *curb* demand.",
  "He learned to *curb* his temper.",
  "The scheme *curbs* waste at source.",
  "Nothing will *curb* the weeds but digging."
 ],
 "foster": [
  "Small classes *foster* real discussion.",
  "The club was set up to *foster* young talent.",
  "Shared meals *foster* a sense of belonging.",
  "The programme *fosters* links between the two schools.",
  "Praise *fosters* confidence more than criticism.",
  "They wanted to *foster* good habits early.",
  "The library *fosters* a love of reading.",
  "Long lunches *foster* the odd friendship.",
  "Trust is *fostered* slowly and lost quickly.",
  "The grant *fosters* new writing."
 ],
 "allocate": [
  "The council will *allocate* the funds next month.",
  "They *allocated* two hours to the discussion.",
  "Each family was *allocated* a plot.",
  "She *allocates* an hour every morning to email.",
  "Rooms are *allocated* on arrival.",
  "The budget *allocates* most of the money to repairs.",
  "He *allocated* the hardest task to himself.",
  "Seats are *allocated* by ballot.",
  "They failed to *allocate* enough time for testing.",
  "The school *allocates* places by distance."
 ],
 "implement": [
  "It took a year to *implement* the new system.",
  "They will *implement* the changes in stages.",
  "The advice was easy to give and hard to *implement*.",
  "The school *implemented* a new marking scheme.",
  "We must *implement* the safety rules properly.",
  "The plan was *implemented* over the summer.",
  "He *implemented* every suggestion from the review.",
  "The policy is simple to *implement*.",
  "They *implemented* a four-day week as a trial.",
  "The fix was *implemented* within a day."
 ],
 "hit the nail on the head": [
  "You have *hit the nail on the head*: it is the noise, not the hours.",
  "She *hit the nail on the head* when she said he was homesick.",
  "That comment *hit the nail on the head*.",
  "He *hit the nail on the head* about the real cost.",
  "The review *hit the nail on the head*.",
  "You *hit the nail on the head* with that question.",
  "Her diagnosis *hit the nail on the head* first time.",
  "The article *hits the nail on the head* about rents.",
  "He rarely says much, but he *hit the nail on the head* there.",
  "That *hit the nail on the head* and ended the argument."
 ],
 "prioritise": [
  "With so little time, you have to *prioritise*.",
  "The hospital *prioritises* the most urgent cases.",
  "She *prioritised* sleep over studying and did better.",
  "We should *prioritise* the roof before the paint.",
  "The list helps him *prioritise* each morning.",
  "They *prioritised* safety over speed.",
  "Schools were *prioritised* for the new funding.",
  "He struggles to *prioritise* when everything feels urgent.",
  "The team *prioritised* the bugs that lost data.",
  "Learn to *prioritise* and the week gets shorter."
 ],
 "advocate": [
  "She has long *advocated* shorter working weeks.",
  "He *advocates* walking rather than driving to school.",
  "The group *advocates* for cleaner rivers.",
  "Doctors *advocate* early screening.",
  "He *advocated* patience, and he was right.",
  "The charity *advocates* on behalf of tenants.",
  "She *advocated* a slower, safer approach.",
  "Few people *advocate* raising the fee.",
  "They *advocate* teaching cooking in schools.",
  "He *advocated* keeping the old building."
 ],
 "attribute": [
  "She *attributes* her recovery to daily walking.",
  "He *attributed* the mistake to tiredness.",
  "The painting is *attributed* to a pupil of the master.",
  "They *attribute* the rise in sales to the advert.",
  "Do not *attribute* to malice what is probably haste.",
  "The delay was *attributed* to bad weather.",
  "She *attributes* her calm to years of practice.",
  "The quote is wrongly *attributed* to Churchill.",
  "He *attributed* the win to the whole squad.",
  "Experts *attribute* the damage to the storm."
 ],
 "exemplify": [
  "That building *exemplifies* the style of the period.",
  "Her career *exemplifies* what hard work can do.",
  "The recipe *exemplifies* simple home cooking.",
  "This case *exemplifies* the problem with the rules.",
  "He *exemplifies* everything the club stands for.",
  "The photograph *exemplifies* her later work.",
  "That answer *exemplifies* the confusion.",
  "The village *exemplifies* rural life in the region.",
  "Her kindness *exemplified* the spirit of the place.",
  "The design *exemplifies* function over decoration."
 ],
 "out of the blue": [
  "He rang *out of the blue* after fifteen years.",
  "The offer came *out of the blue*.",
  "She turned up *out of the blue* on a Tuesday.",
  "*Out of the blue*, the engine cut out.",
  "The letter arrived *out of the blue*.",
  "He quit *out of the blue* with no explanation.",
  "A cheque came *out of the blue* and saved them.",
  "The storm hit *out of the blue*.",
  "*Out of the blue*, she asked him to marry her.",
  "The news came *out of the blue* on a quiet morning."
 ],
 "perpetuate": [
  "Such adverts only *perpetuate* an old stereotype.",
  "The system *perpetuates* the very gap it claims to close.",
  "Repeating the story *perpetuates* the myth.",
  "Poor housing *perpetuates* ill health.",
  "They did not want to *perpetuate* the argument.",
  "The prize *perpetuates* his name.",
  "Silence *perpetuates* the problem.",
  "The custom was *perpetuated* by each generation.",
  "Bad data *perpetuates* bad decisions.",
  "The fee *perpetuates* an unfair advantage."
 ],
 "scrutinise": [
  "The auditors will *scrutinise* every receipt.",
  "She *scrutinised* the contract before signing.",
  "Journalists *scrutinised* the figures for days.",
  "He *scrutinised* the photograph for clues.",
  "The panel *scrutinises* each application twice.",
  "They *scrutinised* the plan and found two flaws.",
  "Buyers *scrutinise* the survey carefully.",
  "The committee *scrutinised* the spending.",
  "He *scrutinised* her face for a reaction.",
  "Every claim is *scrutinised* before publication."
 ],
 "overhaul": [
  "The engine needs a complete *overhaul*.",
  "They plan to *overhaul* the booking system.",
  "The kitchen had a much-needed *overhaul*.",
  "The rules were given a thorough *overhaul*.",
  "He *overhauled* the old bike over the winter.",
  "The department is due an *overhaul*.",
  "A full *overhaul* would cost more than the car.",
  "They *overhauled* the timetable after complaints.",
  "The website *overhaul* took three months.",
  "The heating system needs an *overhaul* before winter."
 ],
 "streamline": [
  "They *streamlined* the process and cut the wait in half.",
  "The company wants to *streamline* its paperwork.",
  "A single form would *streamline* the whole thing.",
  "He *streamlined* the route to save fuel.",
  "The new layout *streamlines* the kitchen.",
  "They *streamlined* the menu to twelve dishes.",
  "The system was *streamlined* last spring.",
  "Fewer steps *streamline* the checkout.",
  "She *streamlined* her morning routine.",
  "The plan is to *streamline* deliveries."
 ],
 "second nature": [
  "After twenty years of driving, it is *second nature* to him.",
  "Checking the mirror becomes *second nature* quickly.",
  "Kneading bread is *second nature* to her now.",
  "Speaking two languages at home made switching *second nature*.",
  "Locking up at night is *second nature* after a while.",
  "The chords became *second nature* after a month.",
  "For a nurse, that check is *second nature*.",
  "Counting change was *second nature* before the machines.",
  "Getting up at five is *second nature* to a baker.",
  "The route is *second nature* to anyone local."
 ],
 "deter": [
  "A bright light will *deter* most burglars.",
  "The fine did not *deter* him at all.",
  "Bad reviews *deterred* a lot of customers.",
  "Nothing could *deter* her from applying.",
  "The steep path *deters* casual walkers.",
  "Higher fees *deter* some students entirely.",
  "A dog in the yard *deters* trouble.",
  "The cold did not *deter* the swimmers.",
  "Long forms *deter* people from claiming.",
  "The warning signs failed to *deter* anyone."
 ],
 "offset": [
  "The extra cost was *offset* by lower fuel bills.",
  "Good weather *offset* a slow start to the season.",
  "They planted trees to *offset* the emissions.",
  "The loss was *offset* by a strong December.",
  "Longer hours are *offset* by an extra day off.",
  "The grant *offsets* most of the rent.",
  "Savings on heating *offset* the price of the work.",
  "Her calm *offset* his panic nicely.",
  "The rise in wages was *offset* by inflation.",
  "Free parking *offsets* the distance from town."
 ],
 "galvanise": [
  "The news *galvanised* the whole neighbourhood into action.",
  "One speech *galvanised* the campaign.",
  "The threat of closure *galvanised* the members.",
  "A single goal *galvanised* the team.",
  "The photograph *galvanised* public opinion.",
  "Her example *galvanised* the younger staff.",
  "The deadline finally *galvanised* him.",
  "The letter *galvanised* hundreds of volunteers.",
  "Bad results *galvanised* the department.",
  "The flood *galvanised* the village into rebuilding."
 ],
 "permeate": [
  "The smell of baking *permeated* the whole house.",
  "Damp had *permeated* the lower walls.",
  "A quiet optimism *permeates* her writing.",
  "Rain *permeated* the old canvas.",
  "The music *permeated* every room.",
  "Doubt began to *permeate* the team.",
  "Oil had *permeated* the concrete floor.",
  "The scent of pine *permeates* the air here.",
  "Her influence *permeates* the whole collection.",
  "Cold *permeated* the thin walls."
 ],
 "a steep learning curve": [
  "The first month was *a steep learning curve*, but she managed.",
  "Moving into management is *a steep learning curve*.",
  "It was *a steep learning curve* learning to sail.",
  "New parents face *a steep learning curve*.",
  "The software has *a steep learning curve*.",
  "He described the year as *a steep learning curve*.",
  "Running a shop was *a steep learning curve* for them.",
  "Expect *a steep learning curve* in the first fortnight.",
  "It is *a steep learning curve*, but it flattens out.",
  "The job was *a steep learning curve* and worth it."
 ],
 "reconcile": [
  "It is hard to *reconcile* those two accounts of the evening.",
  "The brothers *reconciled* after ten years.",
  "She could not *reconcile* the figures with the receipts.",
  "He had to *reconcile* himself to the loss.",
  "The two sides finally *reconciled*.",
  "How do you *reconcile* the cost with the benefit?",
  "They *reconciled* their differences over dinner.",
  "It is difficult to *reconcile* his words with his actions.",
  "The accountant *reconciled* the books each month.",
  "She never *reconciled* herself to city life."
 ],
 "incentive": [
  "There is little *incentive* to recycle if it costs more.",
  "The bonus was a real *incentive* to finish early.",
  "Cheap season tickets are an *incentive* to take the train.",
  "He had no *incentive* to stay after the pay cut.",
  "The scheme offers an *incentive* to insulate your loft.",
  "Praise can be a stronger *incentive* than money.",
  "The discount is an *incentive* to book early.",
  "There is every *incentive* to keep the customer.",
  "Tax relief acts as an *incentive* to invest.",
  "A day off was *incentive* enough."
 ],
 "consensus": [
  "After two hours they finally reached a *consensus*.",
  "There is a growing *consensus* that the rule should change.",
  "No *consensus* emerged from the meeting.",
  "The *consensus* was to postpone the trip.",
  "Scientists have reached a broad *consensus* on the cause.",
  "They worked by *consensus* rather than voting.",
  "The committee lacks any *consensus* on the budget.",
  "A *consensus* formed around the simpler plan.",
  "The *consensus* among neighbours was clear.",
  "Building *consensus* took longer than the work itself."
 ],
 "discrepancy": [
  "There was a *discrepancy* between the two accounts of the night.",
  "The audit found a small *discrepancy* in the till.",
  "A *discrepancy* in the dates gave him away.",
  "She noticed a *discrepancy* between the quote and the bill.",
  "The *discrepancy* turned out to be a typing error.",
  "There is a clear *discrepancy* in the figures.",
  "They explained the *discrepancy* as a rounding error.",
  "A *discrepancy* of ten pounds held up the whole audit.",
  "The *discrepancy* between promise and delivery was obvious.",
  "Any *discrepancy* must be reported the same day."
 ],
 "a grey area": [
  "Whether that counts as overtime is *a grey area*.",
  "The law here is *a grey area*.",
  "Tipping abroad can be *a grey area*.",
  "It is *a grey area* whether the guarantee still applies.",
  "That kind of expense is *a grey area* at work.",
  "The rules leave *a grey area* around subletting.",
  "Ownership of the fence is *a grey area*.",
  "Working from abroad is *a grey area* for tax.",
  "It falls into *a grey area* nobody wants to test.",
  "The deadline is *a grey area* in the contract."
 ],
 "disparity": [
  "There is a wide *disparity* in pay between the two branches.",
  "The *disparity* in results surprised the teachers.",
  "A growing *disparity* separates the two regions.",
  "The *disparity* between the estimate and the bill was huge.",
  "There is a real *disparity* in access to transport.",
  "The report highlights the *disparity* in funding.",
  "The *disparity* in age did not matter to them.",
  "A *disparity* in experience showed in the first half.",
  "The *disparity* narrowed over the decade.",
  "Such a *disparity* in prices is hard to explain."
 ],
 "implication": [
  "Nobody had thought through the *implication* of closing the road.",
  "The *implication* of his remark was clear enough.",
  "There are serious *implications* for small businesses.",
  "She resented the *implication* that she had lied.",
  "The *implications* of the ruling are still unclear.",
  "He missed the *implication* entirely.",
  "The *implication* was that the money had gone.",
  "Consider the *implication* before you agree.",
  "The *implications* for staffing are significant.",
  "There was an *implication* of blame in her tone."
 ],
 "constraint": [
  "Time was the main *constraint* on the project.",
  "They worked within a tight budget *constraint*.",
  "The main *constraint* is the size of the kitchen.",
  "Space is a real *constraint* in a flat that small.",
  "The *constraint* was staff, not money.",
  "Legal *constraints* slowed the sale.",
  "He works best with a *constraint* or two.",
  "The only *constraint* is the ceiling height.",
  "Weather is the biggest *constraint* on the schedule.",
  "Without that *constraint*, the design would be dull."
 ],
 "drawback": [
  "The only *drawback* is that it takes an hour to heat up.",
  "Every option has a *drawback* somewhere.",
  "The main *drawback* of the flat is the noise.",
  "A real *drawback* is the lack of parking.",
  "The *drawback* to cycling here is the hills.",
  "There is one *drawback*: it needs charging daily.",
  "The *drawback* of an early flight is the alarm.",
  "Cost is the obvious *drawback*.",
  "A small *drawback* is that the parts are rare.",
  "The *drawback* became clear in the first winter."
 ],
 "a wake-up call": [
  "The bill was *a wake-up call* about how much they were spending.",
  "His test results were *a wake-up call*.",
  "Losing that match was *a wake-up call* for the squad.",
  "The near miss was *a wake-up call* for the whole industry.",
  "The flood was *a wake-up call* for the council.",
  "Her comment was *a wake-up call* he needed.",
  "The audit was *a wake-up call* about their record keeping.",
  "That winter was *a wake-up call* about insulation.",
  "The review was *a wake-up call*, and they acted on it.",
  "It took *a wake-up call* to change his habits."
 ],
 "catalyst": [
  "The documentary was the *catalyst* for the whole campaign.",
  "Her arrival was the *catalyst* for change in the office.",
  "The closure acted as a *catalyst* for the protest.",
  "A single email became the *catalyst* for the reform.",
  "The fire was the *catalyst* for new safety rules.",
  "His book was the *catalyst* for a wider debate.",
  "The grant was a *catalyst* for the whole project.",
  "That meeting was the *catalyst* for their partnership.",
  "The storm was a *catalyst* for the sea defences.",
  "One bad season became the *catalyst* for a rebuild."
 ],
 "threshold": [
  "Her pain *threshold* is remarkably high.",
  "Income above that *threshold* is taxed differently.",
  "The noise never crossed the *threshold* for a complaint.",
  "He stopped at the *threshold* and knocked.",
  "The *threshold* for free delivery is thirty pounds.",
  "They set a low *threshold* for referral.",
  "Sales passed the *threshold* in November.",
  "The *threshold* for entry was lowered this year.",
  "Below that *threshold*, nothing happens.",
  "She stood on the *threshold*, unsure whether to enter."
 ],
 "backlash": [
  "There was a *backlash* from parents over the new uniform.",
  "The advert caused an immediate *backlash*.",
  "The price rise provoked a *backlash* from regulars.",
  "He faced a *backlash* after the interview.",
  "The council expected a *backlash* and got one.",
  "A *backlash* forced them to reverse the decision.",
  "The *backlash* online lasted a week.",
  "There was little *backlash*, to everyone surprise.",
  "The rule change triggered a *backlash* among staff.",
  "They underestimated the *backlash* from the village."
 ],
 "play it by ear": [
  "We have no fixed plan; we will *play it by ear*.",
  "Let us *play it by ear* and see what the weather does.",
  "He prefers to *play it by ear* on holiday.",
  "They *played it by ear* and it worked out.",
  "With a baby you often have to *play it by ear*.",
  "We will *play it by ear* about dinner.",
  "She likes to *play it by ear* rather than book ahead.",
  "The team *played it by ear* after the injury.",
  "Nothing is booked, so we *play it by ear*.",
  "Let us *play it by ear* until Friday."
 ],
 "trade-off": [
  "There is always a *trade-off* between speed and quality.",
  "The *trade-off* is a smaller garden for a shorter commute.",
  "Every design involves a *trade-off* somewhere.",
  "The *trade-off* was less pay for more freedom.",
  "Choosing the lighter tent is a *trade-off* with warmth.",
  "That is the *trade-off* you accept with an old house.",
  "The *trade-off* between cost and comfort was obvious.",
  "There is a *trade-off* between range and weight.",
  "He understood the *trade-off* and chose time.",
  "The *trade-off* is more storage but a slower machine."
 ],
 "autonomy": [
  "The team was given real *autonomy* over its own budget.",
  "She values the *autonomy* of working for herself.",
  "The region has a degree of *autonomy* in education.",
  "Teachers asked for more *autonomy* in the classroom.",
  "The job offers *autonomy* but little support.",
  "Losing his licence cost him his *autonomy*.",
  "The branch has *autonomy* over opening hours.",
  "*Autonomy* matters more to her than promotion.",
  "They granted the unit full *autonomy*.",
  "With *autonomy* comes responsibility."
 ],
 "infrastructure": [
  "The town needs better *infrastructure* before more houses are built.",
  "Ageing *infrastructure* caused the burst pipe.",
  "Investment in *infrastructure* created hundreds of jobs.",
  "The island *infrastructure* struggles in summer.",
  "Digital *infrastructure* is poor in the valley.",
  "They repaired the *infrastructure* after the flood.",
  "Roads and rail are the obvious *infrastructure* here.",
  "The festival builds its own *infrastructure* each year.",
  "Without the *infrastructure*, the plan cannot work.",
  "Rural *infrastructure* has been neglected for decades."
 ],
 "prevalence": [
  "The *prevalence* of damp in old flats surprised the surveyor.",
  "Studies track the *prevalence* of the illness by county.",
  "The *prevalence* of cars has reshaped the town.",
  "He noted the *prevalence* of short contracts.",
  "The *prevalence* of English in the area is high.",
  "They measured the *prevalence* of the weed.",
  "The *prevalence* of mobile payment is now near total.",
  "*Prevalence* rises sharply in the winter.",
  "The *prevalence* of the accent is falling.",
  "Researchers compared the *prevalence* across regions."
 ],
 "the best of both worlds": [
  "Living on the edge of town gives them *the best of both worlds*.",
  "Working two days at home is *the best of both worlds*.",
  "The hybrid car offers *the best of both worlds*.",
  "A cottage near the station is *the best of both worlds*.",
  "She wanted *the best of both worlds* and nearly got it.",
  "The arrangement gave him *the best of both worlds*.",
  "A folding bike is *the best of both worlds* for commuters.",
  "Term-time work is *the best of both worlds* for parents.",
  "The extension gave them *the best of both worlds*.",
  "It felt like *the best of both worlds* that summer."
 ],
 "adversity": [
  "She showed great courage in the face of *adversity*.",
  "The team grew stronger through *adversity*.",
  "He met *adversity* with quiet patience.",
  "*Adversity* early on shaped the whole family.",
  "The village pulled together in *adversity*.",
  "Years of *adversity* had not made him bitter.",
  "They learned more from *adversity* than success.",
  "He speaks openly about the *adversity* he faced.",
  "*Adversity* tests a friendship quickly.",
  "The film is about ordinary people facing *adversity*."
 ],
 "resilience": [
  "The *resilience* of the community was remarkable after the flood.",
  "Her *resilience* got her through a difficult year.",
  "The plant shows surprising *resilience* in poor soil.",
  "Building *resilience* takes time and rest.",
  "The economy showed more *resilience* than expected.",
  "Children have a *resilience* adults often underestimate.",
  "*Resilience* is not the same as never struggling.",
  "The team showed real *resilience* after going two down.",
  "The old bridge has remarkable *resilience*.",
  "Sleep is the foundation of *resilience*."
 ],
 "paradox": [
  "It is a *paradox* that the busiest people find time to help.",
  "The *paradox* is that spending less took more effort.",
  "There is a *paradox* at the heart of the plan.",
  "The *paradox* of choice is that too much of it paralyses you.",
  "She pointed out the *paradox* in his argument.",
  "It is a *paradox* that the quietest room felt loudest.",
  "The whole system rests on a *paradox*.",
  "He enjoyed the *paradox* of a cold summer.",
  "A neat *paradox*: the shortcut took longer.",
  "The *paradox* of the rule is that it helped nobody."
 ],
 "dichotomy": [
  "There is a false *dichotomy* between working hard and resting well.",
  "The old *dichotomy* of town and country no longer holds.",
  "He rejects the *dichotomy* between art and craft.",
  "The *dichotomy* in the report is too neat to be true.",
  "A simple *dichotomy* hides a lot of middle ground.",
  "The film explores the *dichotomy* between duty and desire.",
  "That *dichotomy* leaves most people out.",
  "She questioned the *dichotomy* the survey assumed.",
  "The *dichotomy* between the two camps deepened.",
  "Any such *dichotomy* is a simplification."
 ],
 "see eye to eye": [
  "They rarely *see eye to eye* on money.",
  "The two managers never *saw eye to eye*.",
  "We do not *see eye to eye* about politics, but we get on.",
  "They finally *saw eye to eye* over dinner.",
  "He and his brother *see eye to eye* on almost nothing.",
  "The partners *see eye to eye* on the important things.",
  "They did not *see eye to eye* about the colour.",
  "It helps that we *see eye to eye* on the basics.",
  "They *saw eye to eye* once the figures were clear.",
  "The neighbours never *saw eye to eye* about the hedge."
 ],
 "nuance": [
  "The translation lost every *nuance* of the original.",
  "There is a *nuance* here that the summary misses.",
  "She hears the *nuance* in his voice.",
  "The argument has more *nuance* than the headline suggests.",
  "A good actor finds the *nuance* in a small part.",
  "The debate lacked all *nuance*.",
  "Every *nuance* of the photograph was deliberate.",
  "He explained the *nuance* between the two words.",
  "The report is careful with *nuance*.",
  "That *nuance* changes the whole meaning."
 ],
 "epiphany": [
  "She had an *epiphany* halfway through the lecture.",
  "The *epiphany* came while he was washing up.",
  "It was a small *epiphany*, but it changed his career.",
  "He described the moment as an *epiphany*.",
  "Her *epiphany* was that nobody was watching.",
  "The trip led to an *epiphany* about what he wanted.",
  "An *epiphany* arrived at four in the morning.",
  "The book gave her an *epiphany* about her father.",
  "That conversation was an *epiphany* for both of them.",
  "His *epiphany* was simple: start earlier."
 ],
 "affinity": [
  "She felt an immediate *affinity* with the place.",
  "He has a natural *affinity* for languages.",
  "There is an *affinity* between the two styles.",
  "Her *affinity* with animals was obvious.",
  "He felt an *affinity* with the older workers.",
  "The plant has an *affinity* for chalky soil.",
  "They share an *affinity* for early mornings.",
  "An *affinity* for numbers made the job easy.",
  "She felt no *affinity* with the city at all.",
  "Their *affinity* grew over the summer."
 ],
 "vivid": [
  "He gave a *vivid* description of the market.",
  "The dream was so *vivid* she wrote it down.",
  "*Vivid* colours filled the whole canvas.",
  "She has a *vivid* memory of that afternoon.",
  "The writing is *vivid* without being showy.",
  "A *vivid* red door marked the house.",
  "His account was *vivid* enough to picture.",
  "The garden was *vivid* after the rain.",
  "She has a *vivid* imagination.",
  "The photograph is unusually *vivid*."
 ],
 "food for thought": [
  "The talk gave everyone plenty of *food for thought*.",
  "His question was real *food for thought*.",
  "The article offers *food for thought* about commuting.",
  "That comment was *food for thought* on the way home.",
  "The report is *food for thought* for the council.",
  "She left them with *food for thought*.",
  "The documentary was *food for thought*.",
  "There is *food for thought* in the last chapter.",
  "His advice was *food for thought* rather than an answer.",
  "The visit gave us *food for thought*."
 ],
 "immersive": [
  "The exhibition was fully *immersive*, with sound in every room.",
  "It is an *immersive* novel you cannot put down.",
  "The course offers an *immersive* week in Spanish.",
  "The game is genuinely *immersive*.",
  "An *immersive* soundtrack made the film.",
  "The theatre piece was *immersive* and unsettling.",
  "She prefers *immersive* learning to textbooks.",
  "The *immersive* display filled the whole hall.",
  "It was an *immersive* experience from the door onwards.",
  "The museum built an *immersive* replica of the street."
 ],
 "exhilarating": [
  "The ride down the hill was *exhilarating*.",
  "It was *exhilarating* to finish after eight months.",
  "The first swim of the year is *exhilarating*.",
  "She found the speed *exhilarating* rather than frightening.",
  "The crowd made the match *exhilarating*.",
  "An *exhilarating* wind came off the sea.",
  "The climb was hard and *exhilarating*.",
  "It was *exhilarating* to sing with a choir again.",
  "The opening night was *exhilarating*.",
  "Driving that road is *exhilarating* in good weather."
 ],
 "daunting": [
  "The pile of forms looked *daunting*.",
  "Starting again at forty felt *daunting*.",
  "The climb is *daunting* from below.",
  "A *daunting* amount of work remained.",
  "The interview was less *daunting* than expected.",
  "It is *daunting* to speak in front of hundreds.",
  "The reading list was *daunting* at first.",
  "She found the first week *daunting*.",
  "The task seemed *daunting* until they split it up.",
  "A *daunting* silence followed the question."
 ],
 "desperate": [
  "He was *desperate* for work after six months.",
  "She made a *desperate* attempt to save the plant.",
  "They were *desperate* to get home before dark.",
  "The situation is *desperate* in the outer villages.",
  "A *desperate* search went on all night.",
  "He is *desperate* for a decent night of sleep.",
  "The team made a *desperate* final push.",
  "She sounded *desperate* on the phone.",
  "They were *desperate* not to lose the house.",
  "A *desperate* shortage of nurses hit the ward."
 ],
 "mundane": [
  "Most of the job is fairly *mundane*.",
  "She finds something pleasing in *mundane* chores.",
  "The film makes the *mundane* look beautiful.",
  "A *mundane* Tuesday turned out to be memorable.",
  "He escaped the *mundane* by walking at dawn.",
  "The meeting covered *mundane* matters only.",
  "Even *mundane* work needs doing well.",
  "Her paintings take a *mundane* subject seriously.",
  "The reason was disappointingly *mundane*.",
  "*Mundane* details make a story believable."
 ],
 "break the ice": [
  "A bad joke helped *break the ice* at the meeting.",
  "She *broke the ice* by asking about his dog.",
  "Someone had to *break the ice*, so he did.",
  "The game was designed to *break the ice*.",
  "Coffee helped *break the ice* with the new team.",
  "He *broke the ice* with a story about the trains.",
  "It took an hour to *break the ice*.",
  "A shared taxi *broke the ice* nicely.",
  "She used a question to *break the ice*.",
  "Nothing could *break the ice* that evening."
 ],
 "tedious": [
  "Waiting two hours at the airport was *tedious*.",
  "The form was long and *tedious*.",
  "Sanding the floor is *tedious* but worth it.",
  "The lecture grew *tedious* after twenty minutes.",
  "A *tedious* drive across flat country.",
  "Checking every figure is *tedious* work.",
  "The meeting was *tedious* and achieved nothing.",
  "He finds ironing unbearably *tedious*.",
  "The journey is *tedious* without music.",
  "A *tedious* wait ended with good news."
 ],
 "overwhelming": [
  "The response to the appeal was *overwhelming*.",
  "She felt an *overwhelming* urge to go home.",
  "The evidence was *overwhelming*.",
  "The smell of lilies was *overwhelming*.",
  "There was *overwhelming* support for the plan.",
  "The workload became *overwhelming* in March.",
  "He won by an *overwhelming* margin.",
  "The kindness shown was *overwhelming*.",
  "The noise was *overwhelming* near the stage.",
  "An *overwhelming* sense of relief followed."
 ],
 "nostalgic": [
  "The smell of coal smoke makes him *nostalgic*.",
  "She felt *nostalgic* looking at the old photographs.",
  "The song is deliberately *nostalgic*.",
  "He gets *nostalgic* about the corner shop.",
  "A *nostalgic* mood settled over the reunion.",
  "The film is *nostalgic* without being sentimental.",
  "She is *nostalgic* for a place she barely knew.",
  "The menu was *nostalgic*, full of school puddings.",
  "He felt *nostalgic* walking past his old flat.",
  "*Nostalgic* adverts sell surprisingly well."
 ],
 "serene": [
  "The lake was *serene* at six in the morning.",
  "She stayed *serene* throughout the argument.",
  "A *serene* expression never left his face.",
  "The garden is *serene* even in winter.",
  "The chapel felt *serene* and cool.",
  "He has a *serene* way of dealing with chaos.",
  "The valley looked *serene* from above.",
  "Her *serene* voice calmed the room.",
  "It was a *serene* evening after a hard week.",
  "The sea was unusually *serene*."
 ],
 "burn the candle at both ends": [
  "He has been *burning the candle at both ends* and it shows.",
  "You cannot *burn the candle at both ends* for a whole term.",
  "She *burned the candle at both ends* during the exams.",
  "Working nights and studying days means *burning the candle at both ends*.",
  "He *burns the candle at both ends* every December.",
  "They warned her about *burning the candle at both ends*.",
  "After a year of *burning the candle at both ends*, he stopped.",
  "New parents often *burn the candle at both ends*.",
  "She was *burning the candle at both ends* and fell ill.",
  "Stop *burning the candle at both ends* before you crash."
 ],
 "chaotic": [
  "The kitchen was *chaotic* on the first night.",
  "Traffic was *chaotic* after the match.",
  "His desk is *chaotic* but he finds everything.",
  "The move was *chaotic* from start to finish.",
  "A *chaotic* morning ended in a quiet afternoon.",
  "The meeting became *chaotic* after ten minutes.",
  "The station was *chaotic* during the strike.",
  "Their first year was *chaotic* and happy.",
  "The weather made the schedule *chaotic*.",
  "It was *chaotic*, but nothing was lost."
 ],
 "desolate": [
  "The moor looked *desolate* in February.",
  "The old station is *desolate* now.",
  "A *desolate* beach stretched for miles.",
  "She felt *desolate* after the news.",
  "The street was *desolate* at that hour.",
  "The site is *desolate* since the factory closed.",
  "A *desolate* wind blew across the field.",
  "The house stood *desolate* for years.",
  "The landscape is beautiful and *desolate*.",
  "He sounded *desolate* on the phone."
 ],
 "luminous": [
  "The moon was *luminous* over the water.",
  "Her skin looked *luminous* in that light.",
  "The dial is *luminous*, so you can read it at night.",
  "A *luminous* green moss covered the stones.",
  "The painting has a *luminous* quality.",
  "Snow made the whole garden *luminous*.",
  "The stained glass was *luminous* at noon.",
  "A *luminous* strip marks the path.",
  "The sky was *luminous* just after sunset.",
  "Her performance was *luminous*."
 ],
 "ephemeral": [
  "Snow here is *ephemeral* and gone by noon.",
  "Fame can be *ephemeral*.",
  "The blossom is *ephemeral*, a fortnight at most.",
  "Their friendship proved *ephemeral*.",
  "He photographs *ephemeral* things like frost.",
  "The exhibition celebrates *ephemeral* art.",
  "That mood was *ephemeral* but real.",
  "Online trends are *ephemeral*.",
  "The *ephemeral* pools dry up by June.",
  "It was an *ephemeral* pleasure and worth it."
 ],
 "jump on the bandwagon": [
  "Every shop *jumped on the bandwagon* once the show became popular.",
  "He was slow to *jump on the bandwagon* and glad of it.",
  "Brands *jump on the bandwagon* within days now.",
  "She refused to *jump on the bandwagon*.",
  "They *jumped on the bandwagon* after the first success.",
  "It is easy to *jump on the bandwagon* and hard to stay.",
  "Half the town *jumped on the bandwagon*.",
  "He *jumped on the bandwagon* far too late.",
  "Politicians *jumped on the bandwagon* immediately.",
  "The cafe *jumped on the bandwagon* with a new menu."
 ],
 "relentless": [
  "The rain was *relentless* for three days.",
  "Her *relentless* effort finally paid off.",
  "The pressure was *relentless* all season.",
  "He is *relentless* once he starts a project.",
  "A *relentless* noise came from upstairs.",
  "The heat was *relentless* that August.",
  "Their *relentless* questioning wore him down.",
  "The schedule is *relentless* in December.",
  "She kept up a *relentless* pace.",
  "The traffic noise is *relentless* here."
 ],
 "meticulous": [
  "He is *meticulous* about his tools: every one has its own place.",
  "Her notes are *meticulous*.",
  "The restoration was *meticulous* and slow.",
  "A *meticulous* check found the fault.",
  "He keeps *meticulous* records of every job.",
  "The model was built with *meticulous* care.",
  "She is *meticulous* in the kitchen.",
  "*Meticulous* planning made the day easy.",
  "The accounts are *meticulous*.",
  "His *meticulous* handwriting filled the page."
 ],
 "resonate": [
  "Her speech *resonated* with everyone in the hall.",
  "The story *resonates* with anyone who has moved house.",
  "That advice *resonated* long afterwards.",
  "The low note *resonated* through the floor.",
  "The message did not *resonate* with younger voters.",
  "His words *resonate* more now than they did then.",
  "The theme *resonates* across the whole album.",
  "The film *resonated* with parents especially.",
  "The bell *resonated* across the valley.",
  "That idea *resonated* immediately."
 ],
 "evoke": [
  "The smell of pine *evokes* childhood holidays.",
  "The photograph *evoked* a rush of memories.",
  "Her writing *evokes* the coast beautifully.",
  "The music *evokes* a particular summer.",
  "That word *evokes* something very specific.",
  "The room *evoked* a quieter decade.",
  "The painting *evokes* heat and dust.",
  "His voice *evoked* her grandfather.",
  "The film *evokes* the period without copying it.",
  "The taste *evoked* a holiday she had forgotten."
 ],
 "a blessing and a curse": [
  "A good memory is *a blessing and a curse*.",
  "Living above the shop was *a blessing and a curse*.",
  "His height is *a blessing and a curse* on the bus.",
  "The quiet is *a blessing and a curse* out here.",
  "Being the eldest was *a blessing and a curse*.",
  "The phone is *a blessing and a curse* at weekends.",
  "Her honesty is *a blessing and a curse*.",
  "The garden is *a blessing and a curse* in August.",
  "Working from home is *a blessing and a curse*.",
  "Early success was *a blessing and a curse* for him."
 ],
 "yearn": [
  "She *yearned* for the sea after a year inland.",
  "He *yearns* to travel again.",
  "They *yearned* for a quieter life.",
  "I *yearn* for a proper night of sleep.",
  "He *yearned* for news from home.",
  "She *yearned* to play in front of a crowd again.",
  "They *yearn* for the old routine.",
  "He *yearned* for the hills he grew up in.",
  "She *yearns* for a garden of her own.",
  "After weeks of rain, we all *yearned* for sun."
 ],
 "flourish": [
  "The business began to *flourish* after the move.",
  "Herbs *flourish* on that sunny windowsill.",
  "She *flourished* once she changed schools.",
  "The town *flourished* in the nineteenth century.",
  "The choir has *flourished* under the new director.",
  "Roses *flourish* in this soil.",
  "His confidence *flourished* that year.",
  "The market *flourishes* every Saturday.",
  "The project *flourished* with proper funding.",
  "Friendships *flourish* when people show up."
 ],
 "dwindle": [
  "Supplies began to *dwindle* by the third day.",
  "The crowd *dwindled* after the rain started.",
  "His savings *dwindled* over the winter.",
  "Membership has *dwindled* in recent years.",
  "The light *dwindled* as they walked.",
  "Interest *dwindled* once the novelty passed.",
  "The queue *dwindled* to a handful.",
  "Their options were *dwindling* fast.",
  "Attendance *dwindled* each week.",
  "The fire *dwindled* to embers."
 ]
};
